export const COMMON_KEYCODES = [
  { code: 3, name: "HOME" },
  { code: 4, name: "BACK" },
  { code: 7, name: "0" },
  { code: 8, name: "1" },
  { code: 9, name: "2" },
  { code: 10, name: "3" },
  { code: 11, name: "4" },
  { code: 12, name: "5" },
  { code: 13, name: "6" },
  { code: 14, name: "7" },
  { code: 15, name: "8" },
  { code: 16, name: "9" },
  { code: 19, name: "DPAD_UP" },
  { code: 20, name: "DPAD_DOWN" },
  { code: 21, name: "DPAD_LEFT" },
  { code: 22, name: "DPAD_RIGHT" },
  { code: 23, name: "DPAD_CENTER" },
  { code: 24, name: "VOLUME_UP" },
  { code: 25, name: "VOLUME_DOWN" },
  { code: 26, name: "POWER" },
  { code: 29, name: "A" },
  { code: 30, name: "B" },
  { code: 31, name: "C" },
  { code: 32, name: "D" },
  { code: 33, name: "E" },
  { code: 34, name: "F" },
  { code: 35, name: "G" },
  { code: 36, name: "H" },
  { code: 37, name: "I" },
  { code: 38, name: "J" },
  { code: 39, name: "K" },
  { code: 40, name: "L" },
  { code: 41, name: "M" },
  { code: 42, name: "N" },
  { code: 43, name: "O" },
  { code: 44, name: "P" },
  { code: 45, name: "Q" },
  { code: 46, name: "R" },
  { code: 47, name: "S" },
  { code: 48, name: "T" },
  { code: 49, name: "U" },
  { code: 50, name: "V" },
  { code: 51, name: "W" },
  { code: 52, name: "X" },
  { code: 53, name: "Y" },
  { code: 54, name: "Z" },
  { code: 61, name: "TAB" },
  { code: 62, name: "SPACE" },
  { code: 66, name: "ENTER" },
  { code: 67, name: "DEL" },
  { code: 68, name: "GRAVE" },
  { code: 69, name: "MINUS" },
  { code: 70, name: "EQUALS" },
  { code: 71, name: "LEFT_BRACKET" },
  { code: 72, name: "RIGHT_BRACKET" },
  { code: 73, name: "BACKSLASH" },
  { code: 74, name: "SEMICOLON" },
  { code: 75, name: "APOSTROPHE" },
  { code: 76, name: "SLASH" },
  { code: 82, name: "MENU" },
  { code: 84, name: "SEARCH" },
  { code: 87, name: "MEDIA_NEXT" },
  { code: 88, name: "MEDIA_PREVIOUS" },
  { code: 91, name: "MUTE" },
  { code: 92, name: "PAGE_UP" },
  { code: 93, name: "PAGE_DOWN" },
  { code: 111, name: "ESCAPE" },
  { code: 112, name: "FORWARD_DEL" },
  { code: 122, name: "MOVE_HOME" },
  { code: 123, name: "MOVE_END" },
  { code: 124, name: "INSERT" },
  { code: 131, name: "F1" },
  { code: 132, name: "F2" },
  { code: 133, name: "F3" },
  { code: 134, name: "F4" },
  { code: 135, name: "F5" },
  { code: 136, name: "F6" },
  { code: 137, name: "F7" },
  { code: 138, name: "F8" },
  { code: 139, name: "F9" },
  { code: 140, name: "F10" },
  { code: 141, name: "F11" },
  { code: 142, name: "F12" },
  { code: 164, name: "VOLUME_MUTE" },
  { code: 187, name: "APP_SWITCH" },
  { code: 207, name: "CONTACTS" },
  { code: 208, name: "CALENDAR" },
  { code: 209, name: "MUSIC" },
  { code: 210, name: "CALCULATOR" },
  { code: 221, name: "BRIGHTNESS_UP" },
  { code: 220, name: "BRIGHTNESS_DOWN" },
  { code: 223, name: "SLEEP" },
  { code: 224, name: "WAKEUP" },
  { code: 285, name: "REFRESH" },
];

export const DEFAULT_KEY_BINDINGS = [
  { id: "home", label: "Home", keycode: 3, group: "navigation" },
  { id: "back", label: "Back", keycode: 4, group: "navigation" },
  { id: "app_switch", label: "Recent Apps", keycode: 187, group: "navigation" },
  { id: "power", label: "Power", keycode: 26, group: "system" },
  { id: "volume_up", label: "Volume +", keycode: 24, group: "system" },
  { id: "volume_down", label: "Volume -", keycode: 25, group: "system" },
  { id: "menu", label: "Menu", keycode: 82, group: "system" },
  { id: "search", label: "Search", keycode: 84, group: "system" },
  { id: "dpad_up", label: "Up", keycode: 19, group: "dpad" },
  { id: "dpad_down", label: "Down", keycode: 20, group: "dpad" },
  { id: "dpad_left", label: "Left", keycode: 21, group: "dpad" },
  { id: "dpad_right", label: "Right", keycode: 22, group: "dpad" },
  { id: "dpad_center", label: "Center", keycode: 23, group: "dpad" },
  { id: "enter", label: "Enter", keycode: 66, group: "typing" },
  { id: "escape", label: "Escape", keycode: 111, group: "typing" },
  { id: "delete", label: "Delete", keycode: 67, group: "typing" },
  { id: "space", label: "Space", keycode: 62, group: "typing" },
  { id: "copy", label: "Copy", keycode: 278, group: "clipboard" },
  { id: "cut", label: "Cut", keycode: 277, group: "clipboard" },
  { id: "paste", label: "Paste", keycode: 279, group: "clipboard" },
  { id: "notification", label: "Notifications", keycode: 83, group: "system" },
  { id: "settings", label: "Settings", keycode: 176, group: "system" },
];

export const HOST_KEY_TO_ANDROID = {
  Backspace: 67,
  Delete: 112,
  Enter: 66,
  Escape: 111,
  " ": 62,
  ArrowUp: 19,
  ArrowDown: 20,
  ArrowLeft: 21,
  ArrowRight: 22,
  Home: 3,
  End: 123,
  PageUp: 92,
  PageDown: 93,
};
